create table T_CLIENTBUYER (id bigint generated by default as identity (start with 1), documentNumber varchar(255) not null, primary key (id))
create table T_ESTABLISHMENT (id bigint generated by default as identity (start with 1), documentNumber varchar(255) not null, locality_id bigint not null, region_id bigint not null, primary key (id))
create table T_LEG (id bigint generated by default as identity (start with 1), stepOrder integer not null, destination_id bigint not null, origin_id bigint not null, route_id bigint not null, primary key (id))
create table T_LOCALITY (id bigint generated by default as identity (start with 1), coordinateX double not null, coordinateY double not null, primary key (id))
create table T_ORDER (id bigint generated by default as identity (start with 1), destination_id bigint not null, origin_id bigint not null, primary key (id))
create table T_ORDER_ITEM (id bigint generated by default as identity (start with 1), order_id bigint not null, product_id bigint not null, primary key (id))
create table T_PRODUCT (id bigint generated by default as identity (start with 1), categoryTemperature varchar(255) not null, name varchar(255) not null, establishment_id bigint not null, primary key (id))
create table T_REGION (id bigint generated by default as identity (start with 1), polygon CLOB not null, primary key (id))
create table T_REGION_EXTENSION (id bigint generated by default as identity (start with 1), locality_id bigint not null, primary key (id))
create table T_REGION_EXTENSION_ACTUAL_PRODUCTS (regionextension_id bigint not null, product_id bigint not null)
create table T_REGION_EXTENSION_REGIONS (regionextension_id bigint not null, region_id bigint not null)
create table T_REGION_EXTENSION_SUPPORTS (regionextension_id bigint not null, support varchar(255))
create table T_ROUTE (id bigint generated by default as identity (start with 1), status varchar(255) not null, worker_id bigint not null, primary key (id))
create table T_WORKER (id bigint generated by default as identity (start with 1), documentNumber varchar(255) not null, primary key (id))
alter table T_CLIENTBUYER add constraint clientbuyer_documentnumber_uk unique (documentNumber)
alter table T_ESTABLISHMENT add constraint establishment_documentnumber_uk unique (documentNumber)
alter table T_REGION_EXTENSION_ACTUAL_PRODUCTS add constraint UK_44y3xx9n8f0r9dv442jkaysg9 unique (product_id)
alter table T_REGION_EXTENSION_REGIONS add constraint UK_o53ujidlg8p5p5su04xaxo4a0 unique (region_id)
alter table T_WORKER add constraint worker_documentnumber_uk unique (documentNumber)
alter table T_ESTABLISHMENT add constraint establishment_locality_fk foreign key (locality_id) references T_LOCALITY
alter table T_ESTABLISHMENT add constraint establishment_region_fk foreign key (region_id) references T_REGION
alter table T_LEG add constraint leg_destination_fk foreign key (destination_id) references T_LOCALITY
alter table T_LEG add constraint leg_origin_fk foreign key (origin_id) references T_LOCALITY
alter table T_LEG add constraint leg_route_fk foreign key (route_id) references T_ROUTE
alter table T_ORDER add constraint order_destination_fk foreign key (destination_id) references T_LOCALITY
alter table T_ORDER add constraint order_origin_fk foreign key (origin_id) references T_LOCALITY
alter table T_ORDER_ITEM add constraint orderitem_order_fk foreign key (order_id) references T_ORDER
alter table T_ORDER_ITEM add constraint orderitem_product_fk foreign key (product_id) references T_PRODUCT
alter table T_PRODUCT add constraint product_establishment_fk foreign key (establishment_id) references T_ESTABLISHMENT
alter table T_REGION_EXTENSION add constraint regionextension_locality_fk foreign key (locality_id) references T_LOCALITY
alter table T_REGION_EXTENSION_ACTUAL_PRODUCTS add constraint regionextension_actual_products_product_fk foreign key (product_id) references T_PRODUCT
alter table T_REGION_EXTENSION_ACTUAL_PRODUCTS add constraint regionextension_actual_products_regionextension_fk foreign key (regionextension_id) references T_REGION_EXTENSION
alter table T_REGION_EXTENSION_REGIONS add constraint regionextension_regions_region_fk foreign key (region_id) references T_REGION
alter table T_REGION_EXTENSION_REGIONS add constraint regionextension_regions_regionextension_fk foreign key (regionextension_id) references T_REGION_EXTENSION
alter table T_REGION_EXTENSION_SUPPORTS add constraint regionextension_supports_regionextension_fk foreign key (regionextension_id) references T_REGION_EXTENSION
alter table T_ROUTE add constraint route_worker_fk foreign key (worker_id) references T_WORKER
